site_name: iDEC 2025 | LZU-MEDICINE-CHINA

theme:
  name: material
  logo: img/idec-wiki-logo-white-bg.png
  favicon: img/idec-wiki-logo.png

  font:
    text: Inter
    code: JetBrains Mono

  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: "Switch to light mode"

  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - header.autohide
    - toc.integrate
    - toc.follow
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  
  # For MathJax
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  # For MathJax: https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  # For sortable data tables: https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

edit_uri: blob/main/docs/

repo_url: https://github.com/idec-teams/2025_LZU-MEDICINE-CHINA

copyright: Copyright &copy; 2025 iDEC LZU-MEDICINE-CHINA. CC-BY-4.0

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/idec-teams/2025_LZU-MEDICINE-CHINA
      name: GitHub

nav:
  - Home: index.md
  - Team:
      - Members: team/members.md
      - Attributions: team/attributions.md
  - Project:
      - Description: project/description.md
      - Design: project/design.md
      - Contribution: project/contribution.md
      - Implementation: project/implementation.md
      - Safety: project/safety.md
  - Wet Lab:
      - Engineering: wet-lab/engineering.md
      - Notebook: wet-lab/notebook.md
      - Protocol: wet-lab/protocol.md
      - Results: wet-lab/results.md
      - Parts: wet-lab/parts.md
      - Proof of Concept: wet-lab/proof-of-concept.md
  - Human Practices:
      - Integrated Human Practices: human-practices/ihp.md
      - Education: human-practices/education.md
      - Entrepreneurship: human-practices/entrepreneurship.md
      - Inclusivity: human-practices/inclusivity.md
      - Sustainability: human-practices/sustainability.md
      - Collaboration: human-practices/collaboration.md
