site_name: iGEM 2025 | LZU-MEDICINE-CHINA

theme:
  name: material
  logo: img/idec-wiki-logo-white-bg.png
  favicon: img/idec-wiki-logo.png

  palette:
    primary: light blue
    accent: blue

  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow

markdown_extensions:
  - footnotes
  - tables
  - attr_list
  - md_in_html
  
  # For MathJax
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # For MathJax: https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  # For sortable data tables: https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

edit_uri: blob/main/docs/

repo_url: https://github.com/igem-teams/2025_LZU-MEDICINE-CHINA

copyright: Copyright &copy; 2025 iGEM LZU-MEDICINE-CHINA. CC-BY-4.0

nav:
  - Home: index.md
  - Team:
      - Members: team/members.md
      - Attributions: team/attributions.md
  - Project:
      - Description: project/description.md
      - Design: project/design.md
      - Contribution: project/contribution.md
      - Implementation: project/implementation.md
      - Safety: project/safety.md
  - Wet Lab:
      - Engineering: wet-lab/engineering.md
      - Notebook: wet-lab/notebook.md
      - Protocol: wet-lab/protocol.md
      - Results: wet-lab/results.md
      - Parts: wet-lab/parts.md
      - Proof of Concept: wet-lab/proof-of-concept.md
  - Human Practices:
      - Integrated Human Practices: human-practices/ihp.md
      - Education: human-practices/education.md
      - Entrepreneurship: human-practices/entrepreneurship.md
      - Inclusivity: human-practices/inclusivity.md
      - Sustainability: human-practices/sustainability.md
      - Collaboration: human-practices/collaboration.md
